In [5]:
import numpy as np
print(np.__version__)

2.0.2


In [6]:
a=np.array([1,2,3,4,5])
print(a)
print(type(a))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [11]:
twoD=np.array([[1,2,3,4,5],[6,7,8,9,0]])
print(twoD)

[[1 2 3 4 5]
 [6 7 8 9 0]]


In [14]:
ThreeD=np.array([[[1,2,3],[2,3,4],[3,4,5]],[[4,5,6],[5,6,7],[6,7,8]]])
print(ThreeD)
print(ThreeD.ndim)

[[[1 2 3]
  [2 3 4]
  [3 4 5]]

 [[4 5 6]
  [5 6 7]
  [6 7 8]]]
3


In [16]:
d=np.zeros((2,3))
print(d)

[[0. 0. 0.]
 [0. 0. 0.]]


In [17]:
e=np.ones((2,3))
print(e)

[[1. 1. 1.]
 [1. 1. 1.]]


In [18]:
np.full((2,3),7)

array([[7, 7, 7],
       [7, 7, 7]])

In [19]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [25]:
np.arange(0,5,4)

array([0, 4])

In [26]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [27]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [28]:
a=np.array([1,2,3])
print(a.dtype)

int64


In [30]:
b=np.array([1,2,3], dtype=np.float32)
print(b.dtype)

float32


In [31]:
c=a.astype(np.float32)
print(c)

[1. 2. 3.]


In [32]:
a=np.arange(12)
print(a)
b=a.reshape(3,4)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [33]:
c=a.reshape(2,-1)
print(c)
print(c.shape)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
(2, 6)


In [36]:
arr=np.array([[1,2],[3,4]])
print(arr)
print(arr.flatten())  # returns a copy
print(arr.ravel())    # returns a view when possible

[[1 2]
 [3 4]]
[1 2 3 4]
[1 2 3 4]


In [37]:
l1=[1,2,3,3]
l2=[4,5,6,6]
print(l1)
print(l2)
print(l1+l2)

[1, 2, 3, 3]
[4, 5, 6, 6]
[1, 2, 3, 3, 4, 5, 6, 6]


In [39]:
a=np.array([10,20,2,4,5])
b=np.array([4,6,5,3,2])

print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a % b)
print(a ** b)

[14 26  7  7  7]
[ 6 14 -3  1  3]
[ 40 120  10  12  10]
[2.5        3.33333333 0.4        1.33333333 2.5       ]
[2 2 2 1 1]
[   10000 64000000       32       64       25]


In [40]:
a=np.array([10,20,2,4,5])
b=np.array([4,6,5,3,2])

print(a > b)
print(a == b)
print(a <= 2)

[ True  True False  True  True]
[False False False False False]
[False False  True False False]


In [41]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))
print(np.power(a,2))
print(np.mod(a,b))
print(np.abs(np.array([-1,-2,3])))

[14 26  7  7  7]
[ 6 14 -3  1  3]
[ 40 120  10  12  10]
[2.5        3.33333333 0.4        1.33333333 2.5       ]
[100 400   4  16  25]
[2 2 2 1 1]
[1 2 3]


In [43]:
print(a[0])
print(a[3])

b=np.array([[1,2,3],[4,5,6]])
print(b[1,2])

10
4
6


In [44]:
a=np.array([10,20,30,40,50])
print(a[1:4])
print(a[:3])
print(a[2:])

[20 30 40]
[10 20 30]
[30 40 50]


In [45]:
dir(np)

['False_',
 'ScalarType',
 'True_',
 '_CopyMode',
 '_NoValue',
 '__NUMPY_SETUP__',
 '__all__',
 '__array_api_version__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__expired_attributes__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__numpy_submodules__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_core',
 '_distributor_init',
 '_expired_attrs_2_0',
 '_get_promotion_state',
 '_globals',
 '_int_extended_msg',
 '_mat',
 '_msg',
 '_no_nep50_warning',
 '_pyinstaller_hooks_dir',
 '_pytesttester',
 '_set_promotion_state',
 '_specific_msg',
 '_type_info',
 '_typing',
 '_utils',
 'abs',
 'absolute',
 'acos',
 'acosh',
 'add',
 'all',
 'allclose',
 'amax',
 'amin',
 'angle',
 'any',
 'append',
 'apply_along_axis',
 'apply_over_axes',
 'arange',
 'arccos',
 'arccosh',
 'arcsin',
 'arcsinh',
 'arctan',
 'arctan2',
 'arctanh',
 'argmax',
 'argmin',
 'argpartition',
 'argsort',
 'argwhere',
 'a

In [47]:
a=[1,2,3,4,5]
b=[5,4,37,5,4]
print(a)
print(b)
print(np.concatenate([a,b]))
print(np.vstack([a,b]))
print(np.hstack([a,b]))
print(np.stack([a,b],axis=0))

[1, 2, 3, 4, 5]
[5, 4, 37, 5, 4]
[ 1  2  3  4  5  5  4 37  5  4]
[[ 1  2  3  4  5]
 [ 5  4 37  5  4]]
[ 1  2  3  4  5  5  4 37  5  4]
[[ 1  2  3  4  5]
 [ 5  4 37  5  4]]


In [50]:
a=np.arange(9)
np.split(a,3) # size of arr must be divide by size of split

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [52]:
a=[1,23,42,4,5]
np.append(a,[2,3,2,9])

array([ 1, 23, 42,  4,  5,  2,  3,  2,  9])

In [55]:
print(np.sort(a))

[ 1  4  5 23 42]


In [56]:
print(np.unique(a))

[ 1  4  5 23 42]


In [57]:
a[::-1]

[42, 23, 5, 4, 1]

In [59]:
matrix=np.array([[1,2,3],[4,5,6]])
print(matrix)
row_add=np.array([5,6,7])
print(matrix+row_add)

[[1 2 3]
 [4 5 6]]
[[ 6  8 10]
 [ 9 11 13]]
